import { Server } from "miragejs";
import { VtSearchResult } from "@/interface/search";

export default function setupSearchRoutes(server: Server) {
  // VirusTotal IP分析接口
  server.get("/search/virustotal/ip/:ip", (schema, request) => {
    const ip = request.params.ip;
    // 根据ip进行VirusTotal分析...
    // 返回VirusTotal搜索结果
    const result: VtSearchResult = {
      ioc: ip,
      ioc_type: "ip_address",
      attributes: {
        network: "103.171.90.0/23",
        tags: [],
        whois:
          "inetnum: 103.171.90.0 - 103.171.91.255\nnetname: HANA-VN\ndescr: HANA A&B JSC\ndescr: 4/2 Dinh Bo Linh, Group 6, Phu Cuong Ward, Thu Dau Mot City, Binh Duong\nadmin-c: TVH12-AP\ntech-c: TVP6-AP\ncountry: VN\nmnt-by: MAINT-VN-VNNIC\nmnt-irt: IRT-VNNIC-AP\nstatus: ASSIGNED PORTABLE\nlast-modified: 2021-08-10T03:29:20Z\nsource: APNIC\nirt: IRT-VNNIC-AP\naddress: Ha Noi, VietNam\nphone: +84-24-35564944\nfax-no: +84-24-37821462\ne-mail: hm-changed@vnnic.vn\nabuse-mailbox: hm-changed@vnnic.vn\nadmin-c: NTTT1-AP\ntech-c: NTTT1-AP\nauth: # Filtered\nmnt-by: MAINT-VN-VNNIC\nlast-modified: 2017-11-08T09:40:06Z\nsource: APNIC\nperson: Tran Van Hung\naddress: 4/2 Dinh Bo Linh, Group 6, Phu Cuong Ward, Thu Dau Mot City, Binh Duong\ncountry: VN\nphone: +84-938247116\ne-mail: kythuat@exe.vn\nnic-hdl: TVH12-AP\nmnt-by: MAINT-VN-VNNIC\nlast-modified: 2021-08-10T03:19:58Z\nsource: APNIC\nperson: Tran Van Phuong\naddress: 4/2 Dinh Bo Linh, Group 6, Phu Cuong Ward, Thu Dau Mot City, Binh Duong\ncountry: VN\nphone: +84-966444463\ne-mail: kythuat@exe.vn\nnic-hdl: TVP6-AP\nmnt-by: MAINT-VN-VNNIC\nlast-modified: 2021-08-10T03:21:03Z\nsource: APNIC\n",
        whois_date: 1701431330,
        last_analysis_date: 1703617138,
        asn: 140819,
        as_owner:
          "42 Dinh Bo Linh, Group 6, Phu Cuong Ward, Thu Dau Mot City, Binh Duong",
        last_analysis_stats: {
          harmless: 53,
          malicious: 15,
          suspicious: 1,
          undetected: 20,
          timeout: 0,
        },
        last_analysis_results: {
          MalwareURL: {
            category: "malicious",
            result: "malware",
            method: "blacklist",
            engine_name: "MalwareURL",
          },
          CRDF: {
            category: "malicious",
            result: "malicious",
            method: "blacklist",
            engine_name: "CRDF",
          },
          Fortinet: {
            category: "malicious",
            result: "malware",
            method: "blacklist",
            engine_name: "Fortinet",
          },
          Lionic: {
            category: "malicious",
            result: "malicious",
            method: "blacklist",
            engine_name: "Lionic",
          },
          Cyble: {
            category: "malicious",
            result: "malicious",
            method: "blacklist",
            engine_name: "Cyble",
          },
          CyRadar: {
            category: "malicious",
            result: "malicious",
            method: "blacklist",
            engine_name: "CyRadar",
          },
          "Antiy-AVL": {
            category: "malicious",
            result: "malicious",
            method: "blacklist",
            engine_name: "Antiy-AVL",
          },
          CrowdSec: {
            category: "malicious",
            result: "malicious",
            method: "blacklist",
            engine_name: "CrowdSec",
          },
          Cluster25: {
            category: "malicious",
            result: "malicious",
            method: "blacklist",
            engine_name: "Cluster25",
          },
          SOCRadar: {
            category: "malicious",
            result: "malicious",
            method: "blacklist",
            engine_name: "SOCRadar",
          },
          IPsum: {
            category: "malicious",
            result: "malicious",
            method: "blacklist",
            engine_name: "IPsum",
          },
          BitDefender: {
            category: "malicious",
            result: "phishing",
            method: "blacklist",
            engine_name: "BitDefender",
          },
          GreenSnow: {
            category: "malicious",
            result: "malicious",
            method: "blacklist",
            engine_name: "GreenSnow",
          },
          "G-Data": {
            category: "malicious",
            result: "phishing",
            method: "blacklist",
            engine_name: "G-Data",
          },
          "Criminal IP": {
            category: "malicious",
            result: "malicious",
            method: "blacklist",
            engine_name: "Criminal IP",
          },
          AlphaSOC: {
            category: "suspicious",
            result: "suspicious",
            method: "blacklist",
            engine_name: "AlphaSOC",
          },
          "CMC Threat Intelligence": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "CMC Threat Intelligence",
          },
          "Snort IP sample list": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Snort IP sample list",
          },
          ViriBack: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "ViriBack",
          },
          K7AntiVirus: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "K7AntiVirus",
          },
          "CINS Army": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "CINS Army",
          },
          Quttera: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Quttera",
          },
          OpenPhish: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "OpenPhish",
          },
          "VX Vault": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "VX Vault",
          },
          Scantitan: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Scantitan",
          },
          AlienVault: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "AlienVault",
          },
          Sophos: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Sophos",
          },
          Phishtank: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Phishtank",
          },
          Spam404: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Spam404",
          },
          "alphaMountain.ai": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "alphaMountain.ai",
          },
          Seclookup: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Seclookup",
          },
          "Google Safebrowsing": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Google Safebrowsing",
          },
          ADMINUSLabs: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "ADMINUSLabs",
          },
          ESTsecurity: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "ESTsecurity",
          },
          "Juniper Networks": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Juniper Networks",
          },
          "Heimdal Security": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Heimdal Security",
          },
          Trustwave: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Trustwave",
          },
          "Dr.Web": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Dr.Web",
          },
          Emsisoft: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Emsisoft",
          },
          Abusix: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Abusix",
          },
          Webroot: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Webroot",
          },
          Avira: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Avira",
          },
          securolytics: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "securolytics",
          },
          Acronis: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Acronis",
          },
          "Quick Heal": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Quick Heal",
          },
          "Viettel Threat Intelligence": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Viettel Threat Intelligence",
          },
          DNS8: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "DNS8",
          },
          "AILabs (MONITORAPP)": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "AILabs (MONITORAPP)",
          },
          "benkow.cc": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "benkow.cc",
          },
          EmergingThreats: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "EmergingThreats",
          },
          "Chong Lua Dao": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Chong Lua Dao",
          },
          "Yandex Safebrowsing": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Yandex Safebrowsing",
          },
          "Sucuri SiteCheck": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Sucuri SiteCheck",
          },
          "desenmascara.me": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "desenmascara.me",
          },
          URLhaus: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "URLhaus",
          },
          PREBYTES: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "PREBYTES",
          },
          StopForumSpam: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "StopForumSpam",
          },
          Blueliv: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Blueliv",
          },
          ZeroCERT: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "ZeroCERT",
          },
          "Phishing Database": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Phishing Database",
          },
          MalwarePatrol: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "MalwarePatrol",
          },
          Malwared: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Malwared",
          },
          "SCUMWARE.org": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "SCUMWARE.org",
          },
          "malwares.com URL checker": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "malwares.com URL checker",
          },
          Certego: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Certego",
          },
          ESET: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "ESET",
          },
          Threatsourcing: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Threatsourcing",
          },
          ThreatHive: {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "ThreatHive",
          },
          "Bfore.Ai PreCrime": {
            category: "harmless",
            result: "clean",
            method: "blacklist",
            engine_name: "Bfore.Ai PreCrime",
          },
          Bkav: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "Bkav",
          },
          "0xSI_f33d": {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "0xSI_f33d",
          },
          PhishLabs: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "PhishLabs",
          },
          PrecisionSec: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "PrecisionSec",
          },
          "ArcSight Threat Intelligence": {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "ArcSight Threat Intelligence",
          },
          Cyan: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "Cyan",
          },
          SecureBrain: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "SecureBrain",
          },
          "Xcitium Verdict Cloud": {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "Xcitium Verdict Cloud",
          },
          SafeToOpen: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "SafeToOpen",
          },
          AutoShun: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "AutoShun",
          },
          URLQuery: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "URLQuery",
          },
          Ermes: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "Ermes",
          },
          Lumu: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "Lumu",
          },
          zvelo: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "zvelo",
          },
          Kaspersky: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "Kaspersky",
          },
          Segasec: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "Segasec",
          },
          Netcraft: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "Netcraft",
          },
          VIPRE: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "VIPRE",
          },
          PhishFort: {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "PhishFort",
          },
          "Forcepoint ThreatSeeker": {
            category: "undetected",
            result: "unrated",
            method: "blacklist",
            engine_name: "Forcepoint ThreatSeeker",
          },
        },
      },
    };
    return result;
  });

  // ...其他搜索相关路由
}
